### PR TITLE
changelog: restore previous version notes

### PR DESCRIPTION
**Pull request by stokito**

### CODE REVIEW

**Comment by stokito** [comment]
FYI: I pushed the last version to Ubuntu PPA and it was built. Packages will be published soon https://launchpad.net/~stokito/+archive/ubuntu/kadnode/+packages

**Comment by stokito** [comment]
The PPA belongs to me only so only I can publish changes.
In order to let you do this yourself too I created a Team that you can join. 
Since I'll also need a team for my project I called it YurtPage https://launchpad.net/~yurtpage.
And under the team you can create a PPA for the KadNode and set a build recipe.
Sources are already pushed https://code.launchpad.net/~yurtpage/+git/KadNode

Steps to do this are:
Click on "Create packaging recipe"
Use an existing PPA: KadNode
Default distribution series: select first two-four
Run build by clicking on "Request build(s)"


Please confirm if you can create the ppa and set a build recipe.


Next time to make a release you just need to push to the git repo.

**Comment by mwarning** [comment]
hi @stokito, thank you for doing this. I my side I would like to hold off putting effort into packaging until a new version is read, because I am not very confident with the current released implementation.

The current problems are:
* libmbedtls makes several crypto fields inaccessible (no idea how to work around this, maybe casting into hidden fields..) 
* slow or failing resolver logic (I kind of know how to fix this)

**Comment by stokito** [comment]
Sure, I just don't want to be a weak link. This time a upload a new version too late. Previously on Launchpad there was an ability to just specify a GitHub repo directly and it was build and published automatically on a push.
Now the only way to publish is to push directly to the launchpad repo.
This is annoying additional step.
So I can assist you to explain how to deal with the Launchpad, Please write me in https://matrix.to/#/@stokito:matrix.org

> libmbedtls makes several crypto fields inaccessible

I don't now but maybe it would be better to just abandon the mbedtls and use openssl.
Bigger routers like Turris Omnia or GL.Inet anyway use it because they ship with OpenVPN which as far know doesn't really works with the mbedtls.

**Pull request merged**
