### PR TITLE
CMake support

### PR DESCRIPTION
**Pull request by stokito**
The CLion IDE (IntelliJ) works normally only with CMake.
Otherwise I can't debug it.
I added the CMakeList.txt just for this case.
It doesn't work completely so you may not merge it.
Anyway the PR may be useful for others like me

### CODE REVIEW

**Comment by mwarning** [comment]
What does not work? It compiles for me.

**Comment by stokito** [comment]
not all features are migrated: natpmp, libcadnode etc.

**Comment by mwarning** [comment]
ah, ok. understood.

**Comment by stokito** [comment]
The Makefile has this:

    ifeq ($(OS),Windows_NT)
      OBJS += build/unix.o build/windows.o
    else
      OBJS += build/unix.o
    endif

E.g. even for a Windows we need to compile the unix.c file. Is this correct or was made by a mistake?

**Comment by mwarning** [comment]
unix.c is need to compile on Windows since Cygwin is used.

**Comment by stokito** [comment]
so this file is anyway always added then we can move it too list of all core files

**Comment by mwarning** [comment]
Yes, that sounds like a good idea.

**Comment by Neustradamus** [comment]
@stokito: Have you progressed on this PR?

**Comment by mwarning** [comment]
I will close this MR, as the projects will not use cmake for the forseeable future and I do feel motivated to maintain a cmake file.
If someone needs it, we can always point to this MR.

@stokito thank your for the effort though.

**Pull request closed without merging**
