### PR TITLE
Add DNSPROXY code

### PR DESCRIPTION
**Pull request by axxName**
I fixed some style issues as I understand.

And fix please:
char extdns_servers[3][100];

### CODE REVIEW

**Comment by mwarning** [comment]
ok, it looks better now (but some indentation is still broken..).
I will need some time to test the code.

**Comment by mwarning** [comment]
So far, the main issue is that blocking requests interrupt the working of KadNode. When we get many requests, KadNode will block up.

**Comment by axxName** [comment]
Bad news.
This means that the code needs to be rewritten

**Comment by mwarning** [comment]
well, I will give it a try.

**Pull request closed without merging**
